### ISSUE TITLE
Medical professional documentation

### ISSUE THREAD

**Issue by drcandacemakedamoore** [brainspinner/cvasl#135]
@jan-petr , or anyone else, can you please add a few sentences on the goals of the library to the docs\medical-professionals.rst file, so the documentation does not have ....,.
just summarize the goals , and I will then refine it by clarifying what is already coded.

It renders here: https://brainspinner.github.io/cvasl/medical-professionals.html

**Comment by MDijsselhof** [comment]
Accelerated biological ageing is associated with cognitive decline and neurodegenerative disease, and can be identified through neuro-imaging methods and machine learning. This brain-age estimation method, _CVASL_, incorporates traditional structural MRI markers of accelerated biological ageing with cerebrovascular health markers, a major key player in the evolution of cognitive dysfunction, through use of Arterial Spin Labelling MRI, proven to improve accuracy ([Dijsselhof et al.,](https://onlinelibrary.wiley.com/doi/10.1002/hbm.26242)).

The _CVASL_ package utilises structural and cerebrovascular MRI measurements, as outputted by [ExploreASL](https://sites.google.com/view/exploreasl), along with age and sex information to produce estimations of biological brain age. Included are options to pool different MRI datasets, through harmonisation, and visualise outcome measures.
