### ISSUE TITLE
additional algorithms run

### ISSUE THREAD

**Issue by drcandacemakedamoore** [brainspinner/cvasl#144]
AutoCombat (environment specified)

Polynomial (home made)

CovBat (**environment missing**)

ComBat++ 
ComBAT-GAM - non-linear
RELIEF

**Comment by brainspinner** [comment]
AUtocombat, and ComBAT-GAM are done. RELIEF is not neccesary

**Comment by brainspinner** [comment]
@MDijsselhof I'm adding you as an asignee to this because you are the natural reviewer due to the fact you will need to run all the notebooks for these algorithms to get results. Once it goes into review column, please review.

**Comment by drcandacemakedamoore** [comment]
This issue will now only cover neurocombat, open nested combat, autocombat. Other algorithm implementations have their own issue. The issue is partially blocked by waiting for permission on the "H" dataset.

**Comment by drcandacemakedamoore** [comment]
Done.
