### ISSUE TITLE
change  ouputs so negative features

### ISSUE THREAD

**Issue by drcandacemakedamoore** [brainspinner/cvasl#150]
shift all values before and afttear each harmonization algorithm

written in function
assure that all values  > 0

def checker_and_fixer([dataset1, dataset2, ...datasetn], log_or_shift):
   for a data set in dataets:
         per column of any value negative, shift that column in every dataset so no values negative

**Comment by brainspinner** [comment]
blocked due to no implementation yet of some algorithms

**Comment by drcandacemakedamoore** [comment]
spatial COV variance found to be acceptable for partners.
