### ISSUE TITLE
fix testing matrix

### ISSUE THREAD

**Issue by drcandacemakedamoore** [brainspinner/cvasl#153]
testing matrix must include mac, linux and windows (was set away from this on release 1 for emporary technical reasons)

**Comment by drcandacemakedamoore** [comment]
I was able to add Mac but not Windows so far. For review with @egpbos

**Comment by drcandacemakedamoore** [comment]
Fixed with implementation of pytest

**Comment by egpbos** [comment]
You mean it was an issue in a version of pytest?
