### ISSUE TITLE
switch K-fold to double-stratified

### ISSUE THREAD

**Issue by brainspinner** [brainspinner/cvasl#156]

**Comment by brainspinner** [comment]
We already have the function written, just swtich it in the notebooks

**Comment by drcandacemakedamoore** [comment]
Example done already in notebook ml_experiment1a.ipynb on drcandacemakedamoore/new_algo_3 branch. Please continue to change all the relevant notebooks on this branch i.e.  ml_experiment1* ml_experiment2* and ml_experiment3*. Just switch seperated.stratified_one_category_shuffle_split with  seperatedstratified_cat_and_cont_categories_shuffle_split

**Comment by MDijsselhof** [comment]
Done! I haven't touched the code in the abstract folders, as we should keep that the same to be able to replicate results
