### ISSUE TITLE
fix markdown in neuroharmonize notebooks

### ISSUE THREAD

**Issue by brainspinner** [brainspinner/cvasl#160]
Accidentally I wrote "neuroharmony" in these notebooks(all the ones with an E in the title on the endinng e.g. [ml_experiment2ea-neuroharm_topmri_sabre.ipynb](https://github.com/brainspinner/cvasl/blob/develop/harmonization_paper/ml_experiment2ea-neuroharm_topmri_sabre.ipynb))  instead of neuroharmonize in the markdown. This should be changed, and markdown should be proofed for readability in general,

**Comment by MDijsselhof** [comment]
I also changed the name in Legacy and Homemade_and_other to be sure its all correct
